### ISSUE TITLE
Unable to install SVM on Mac OS

### ISSUE THREAD

**Issue by PierrickGT** [web3j/svm#2]
Hi,
I've stumbled upon this tool while reading the Week in Ethereum newsletter.
Sadly, I can't install it on Mac OS since the `svm-darwin.tar` file is missing.

```
Downloading svm...
https://github.com/web3j/svm/releases/download/0.1.2/svm-darwin.tar
Looks like there was an error while trying to download svm
source: no such file or directory: /Users/pierrick/.svm/svm.sh
```

Thank you for this tool and your help.

**Comment by josh-richardson** [comment]
This repository is currently the most updated one, and should work on MacOS. Sorry for not spotting this issue sooner.

https://github.com/josh-richardson/svm
